CREATE TABLE EMPLOYEES (
  ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME   VARCHAR2(100),
  DEPT_ID NUMBER,
  SALARY NUMBER(10,0)
);

CREATE TABLE DEPARTMENTS (
  ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME   VARCHAR2(100),
  LOCATION VARCHAR2(100)
);

INSERT INTO DEPARTMENTS (NAME, LOCATION) VALUES ('Engineering', 'Pune');
INSERT INTO DEPARTMENTS (NAME, LOCATION) VALUES ('Marketing',   'Mumbai');
INSERT INTO DEPARTMENTS (NAME, LOCATION) VALUES ('Finance',     'Delhi');
COMMIT;

INSERT INTO EMPLOYEES (NAME, DEPT_ID, SALARY) VALUES ('Alice', 1, 90000);
INSERT INTO EMPLOYEES (NAME, DEPT_ID, SALARY) VALUES ('Bob',   2, 75000);
INSERT INTO EMPLOYEES (NAME, DEPT_ID, SALARY) VALUES ('Carol', 1, 95000);
COMMIT;
