#!/bin/bash
set -e

echo "=== Step 1: Enable ARCHIVELOG mode ==="
sqlplus -s / as sysdba <<'EOF'
SHUTDOWN IMMEDIATE;
EOF

sqlplus -s / as sysdba <<'EOF'
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL OPEN;
ALTER SYSTEM SWITCH LOGFILE;
EOF

echo "=== Step 2: Enable supplemental logging ==="
sqlplus -s / as sysdba <<'EOF'
ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER SESSION SET CONTAINER=XEPDB1;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
EOF

echo "=== Step 3: Create CDC user C##DBZUSER ==="
sqlplus -s / as sysdba <<'EOF'
CREATE USER C##DBZUSER IDENTIFIED BY dbzpassword
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  CONTAINER=ALL;

GRANT CREATE SESSION        TO C##DBZUSER CONTAINER=ALL;
GRANT SET CONTAINER         TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY TABLE      TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##DBZUSER CONTAINER=ALL;
GRANT LOGMINING             TO C##DBZUSER CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE   TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR   TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE            TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG                 TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE             TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS         TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS     TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS   TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY         TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG        TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION         TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$INSTANCE            TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$PDBS                TO C##DBZUSER CONTAINER=ALL;
COMMIT;
EOF

echo "=== Step 4: Enable supplemental logging on EMPLOYEES table ==="
sqlplus -s appuser/appuser@//localhost:1521/XEPDB1 <<'EOF'
ALTER TABLE EMPLOYEES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
COMMIT;
EOF

echo "=== CDC setup complete ==="
